name: 🚧 Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: 🚧 Build
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: 🚧 Build
        uses: ./.github/actions/build

  web:
    name: ☁️ Build Web
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: 🚧 Build
        uses: ./.github/actions/build
        with:
          script: 'build:web'

  test:
    name: 🧪 Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: 🧱 Install
        uses: ./.github/actions/install

      - name: 🧪 Unit tests
        run: |
          # ================= 🧪 Unit tests =================
          pnpm run test:unit

  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: 🧱 Install
        uses: ./.github/actions/install

      - name: 🧱 Versions
        run: |
          # =================  🔍 Versions  =================
          pnpm exec eslint --version
          pnpm exec prettier --version
          pnpm exec stylelint --version

      - name: 🔍 Check
        run: |
          # =================  🔍 Check  =================
          pnpm run check

      - name: 🧹 Lint
        run: |
          # =================  🧹 Lint  =================
          pnpm run lint

      - name: 🪄 Stylelint
        run: |
          # =================  🪄 Stylelint  =================
          pnpm run style
